resources:
  - name: source-code
    type: git
    check_every: 10s
    source:
      uri: https://github.com/jarlehansen/spring-boot-concourse.git
      branch: master

jobs:
  - name: build
    plan:
    - get: source-code
      trigger: true
    - task: Build project
      privileged: true
      file: source-code/concourse/tasks/build.yml

  - name: deploy
    plan:
    - get: source-code
      passed: [build]
      trigger: true
    - task: Deploy artifact
      file: source-code/concourse/tasks/deploy.yml