resources:
  - name: source-code
    type: git
    source:
      uri: https://github.com/jarlehansen/spring-boot-concourse.git
      branch: master

jobs:
  - name: build
    plan:
    - get: source-code
      trigger: true
    - task: build
      privileged: true
      file: source-code/concourse/tasks/build.yml
    - task: test
      run:
        path: echo
        args: [hello world]