resources:
  - name: git-repo
    type: git
    check_every: 10s
    source:
      uri: https://github.com/derrickchwong/spring-boot-concourse.git
      branch: master
  - name: cf
    type: cf
    source:
      api: {{CF_API}}
      username: {{CF_USER}}
      password: {{CF_PASS}}
      organization: {{CF_ORG}}
      space: {{CF_SPACE}}

jobs:
- name: build
  public: true
  plan:
  - get: git-repo
    trigger: true
  - task: Build project
    file: git-repo/concourse/tasks/build.yml
#  - task: Deploy artifact
#    file: git-repo/concourse/tasks/deploy.yml
  - put: cf
    params:
      manifest: git-repo/manifest.yml
#      current_app_name: spring-music
      path: build-output/spring-boot-concourse-*.jar