resources:
  - name: git-repo
    type: git
    check_every: 10s
    source:
      uri: https://github.com/derrickchwong/spring-boot-concourse.git
      branch: master
  - name: pcf
    type: cf
    source:
      api: {{CF_API}}
      username: {{CF_USER}}
      password: {{CF_PASS}}
      organization: {{CF_ORG}}
      space: {{CF_SPACE}}

jobs:
- name: build
  public: true
  plan:
  - get: git-repo
    trigger: true
  - task: Build project
    file: git-repo/concourse/tasks/build.yml
  - put: pcf
    params:
      manifest: git-repo/manifest.yml
      path: build-output/*.jar