resources:
  - name: source-code
    type: git
    check_every: 10s
    source:
      uri: https://github.com/jarlehansen/spring-boot-concourse.git
      branch: master

jobs:
- name: build
  public: true
  plan:
  - get: source-code
    trigger: true
  - task: Build project
    privileged: true
    file: source-code/concourse/tasks/build.yml
  - task: Deploy artifact
    file: source-code/concourse/tasks/deploy.yml
