platform: linux

image_resource:
  type: docker-image
  source: {repository: java, tag: openjdk-8-alpine}

inputs:
  - name: git-repo

outputs:
  - name: build-output

run:
  path: "git-repo/concourse/tasks/build.sh"