platform: linux

image_resource:
  type: docker-image
  source: {repository: java, tag: openjdk-8-alpine}

inputs:
  - name: source-code

outputs:
  - name: build-output

run:
  path: "source-code/build.sh"