platform: linux

image_resource:
  type: docker-image
  source: {repository: java, tag: openjdk-8-alpine}

inputs:
  - name: source-code

run:
  path: "source-code/gradlew"
  args: ["--build-file", "source-code/build.gradle", "build"]